version: "3.8"
services:
  app:
    build: .
    network_mode: "host"  # Use the host's network stack
    restart: always
    ports:
      - "8021:8021"  # Map port 5112 from container to host
      - "8022:8022"  # Map port 5113 from container to host